package btest

import (
	"fmt"
	"math/rand"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

// FuzzEvent describes a single random input event generated by the fuzzer.
type FuzzEvent struct {
	Kind   string // "key", "mouse", "resize", "tick"
	Key    string // for Kind="key"
	X, Y   int    // for Kind="mouse"
	Button tea.MouseButton
	Cols   int // for Kind="resize"
	Lines  int // for Kind="resize"
}

// String returns a human-readable representation of the event.
func (e FuzzEvent) String() string {
	switch e.Kind {
	case "key":
		return fmt.Sprintf("key(%s)", e.Key)
	case "mouse":
		return fmt.Sprintf("mouse(%d,%d,btn=%d)", e.X, e.Y, e.Button)
	case "resize":
		return fmt.Sprintf("resize(%dx%d)", e.Cols, e.Lines)
	case "tick":
		return "tick"
	default:
		return fmt.Sprintf("unknown(%s)", e.Kind)
	}
}

// FuzzConfig configures the random input generator.
type FuzzConfig struct {
	// Seed for the random number generator. Zero uses a random seed.
	Seed int64

	// Iterations is the number of random events to generate per run.
	// Defaults to 1000.
	Iterations int

	// Cols and Lines set the initial terminal dimensions.
	// Defaults to 80x24.
	Cols  int
	Lines int

	// KeyWeight, MouseWeight, ResizeWeight, TickWeight control the
	// relative probability of each event type. All default to 1.
	KeyWeight    int
	MouseWeight  int
	ResizeWeight int
	TickWeight   int

	// MinCols, MaxCols, MinLines, MaxLines constrain random resize events.
	// Defaults: 20–200 cols, 5–60 lines.
	MinCols  int
	MaxCols  int
	MinLines int
	MaxLines int

	// ExtraKeys are additional key names to include in the random pool
	// beyond the built-in keyMap entries.
	ExtraKeys []string
}

func (c *FuzzConfig) defaults() {
	if c.Iterations <= 0 {
		c.Iterations = 1000
	}
	if c.Cols <= 0 {
		c.Cols = 80
	}
	if c.Lines <= 0 {
		c.Lines = 24
	}
	// Weights: if all are zero, apply equal defaults. If at least one is
	// set, leave zeros as-is (meaning that event type is disabled).
	if c.KeyWeight == 0 && c.MouseWeight == 0 && c.ResizeWeight == 0 && c.TickWeight == 0 {
		c.KeyWeight = 1
		c.MouseWeight = 1
		c.ResizeWeight = 1
		c.TickWeight = 1
	}
	if c.MinCols <= 0 {
		c.MinCols = 20
	}
	if c.MaxCols <= 0 {
		c.MaxCols = 200
	}
	if c.MinLines <= 0 {
		c.MinLines = 5
	}
	if c.MaxLines <= 0 {
		c.MaxLines = 60
	}
}

// FuzzResult holds the outcome of a fuzz run.
type FuzzResult struct {
	// Iterations is the number of events that were applied.
	Iterations int

	// Panicked is true if the model panicked during the run.
	Panicked bool

	// PanicValue holds the recovered panic value, if any.
	PanicValue interface{}

	// PanicEvent is the index of the event that caused the panic.
	PanicEvent int

	// Events is the full sequence of generated events.
	Events []FuzzEvent
}

// FailingSequence returns the events up to and including the panic trigger.
// Returns nil if no panic occurred.
func (r *FuzzResult) FailingSequence() []FuzzEvent {
	if !r.Panicked {
		return nil
	}
	if r.PanicEvent >= len(r.Events) {
		return r.Events
	}
	return r.Events[:r.PanicEvent+1]
}

// FormatSequence returns a human-readable string of a fuzz event sequence.
func FormatSequence(events []FuzzEvent) string {
	var sb strings.Builder
	for i, e := range events {
		if i > 0 {
			sb.WriteString(" → ")
		}
		sb.WriteString(e.String())
	}
	return sb.String()
}

// Fuzz runs a random input sequence against a tea.Model and reports whether
// it panicked. The model is tested inside a TestModel wrapper.
func Fuzz(t testing.TB, model tea.Model, cfg FuzzConfig) *FuzzResult {
	t.Helper()
	cfg.defaults()

	rng := rand.New(rand.NewSource(cfg.Seed)) //nolint:gosec

	// Build the key pool from keyMap + printable ASCII + extra keys.
	keys := buildKeyPool(cfg.ExtraKeys)

	// Build weighted event type selector. Clamp negatives to zero.
	if cfg.KeyWeight < 0 {
		cfg.KeyWeight = 0
	}
	if cfg.MouseWeight < 0 {
		cfg.MouseWeight = 0
	}
	if cfg.ResizeWeight < 0 {
		cfg.ResizeWeight = 0
	}
	if cfg.TickWeight < 0 {
		cfg.TickWeight = 0
	}
	totalWeight := cfg.KeyWeight + cfg.MouseWeight + cfg.ResizeWeight + cfg.TickWeight

	// Generate all events upfront so they can be captured on panic.
	events := make([]FuzzEvent, cfg.Iterations)
	for i := range events {
		events[i] = generateEvent(rng, keys, totalWeight, cfg)
	}

	result := &FuzzResult{
		Events: events,
	}

	tm := NewTestModel(t, model, cfg.Cols, cfg.Lines)

	for i, ev := range events {
		func() {
			defer func() {
				if r := recover(); r != nil {
					result.Panicked = true
					result.PanicValue = r
					result.PanicEvent = i
					result.Iterations = i + 1
				}
			}()
			applyFuzzEvent(tm, ev)
		}()
		if result.Panicked {
			return result
		}
	}

	result.Iterations = cfg.Iterations
	return result
}

// FuzzAndFail runs Fuzz and fails the test if the model panics, printing
// the failing sequence for reproduction.
func FuzzAndFail(t testing.TB, model tea.Model, cfg FuzzConfig) {
	t.Helper()
	result := Fuzz(t, model, cfg)
	if result.Panicked {
		seq := result.FailingSequence()
		t.Fatalf("fuzz: model panicked after %d events: %v\nsequence: %s",
			result.PanicEvent+1, result.PanicValue, FormatSequence(seq))
	}
}

// buildKeyPool constructs the list of key names available for fuzzing.
func buildKeyPool(extra []string) []string {
	keys := make([]string, 0, len(keyMap)+26+len(extra))
	for k := range keyMap {
		keys = append(keys, k)
	}
	// Add printable ASCII characters.
	for c := 'a'; c <= 'z'; c++ {
		keys = append(keys, string(c))
	}
	for c := '0'; c <= '9'; c++ {
		keys = append(keys, string(c))
	}
	keys = append(keys, extra...)
	return keys
}

// generateEvent creates a single random FuzzEvent.
func generateEvent(rng *rand.Rand, keys []string, totalWeight int, cfg FuzzConfig) FuzzEvent {
	roll := rng.Intn(totalWeight)
	switch {
	case roll < cfg.KeyWeight:
		return FuzzEvent{
			Kind: "key",
			Key:  keys[rng.Intn(len(keys))],
		}
	case roll < cfg.KeyWeight+cfg.MouseWeight:
		return FuzzEvent{
			Kind:   "mouse",
			X:      rng.Intn(cfg.MaxCols),
			Y:      rng.Intn(cfg.MaxLines),
			Button: tea.MouseButton(rng.Intn(3)), // left, middle, right
		}
	case roll < cfg.KeyWeight+cfg.MouseWeight+cfg.ResizeWeight:
		cols := cfg.MinCols + rng.Intn(cfg.MaxCols-cfg.MinCols+1)
		lines := cfg.MinLines + rng.Intn(cfg.MaxLines-cfg.MinLines+1)
		return FuzzEvent{
			Kind:  "resize",
			Cols:  cols,
			Lines: lines,
		}
	default:
		return FuzzEvent{Kind: "tick"}
	}
}

// applyFuzzEvent sends a single fuzz event to the TestModel.
func applyFuzzEvent(tm *TestModel, ev FuzzEvent) {
	switch ev.Kind {
	case "key":
		tm.SendKey(ev.Key)
	case "mouse":
		tm.SendMouse(ev.X, ev.Y, ev.Button)
	case "resize":
		tm.SendResize(ev.Cols, ev.Lines)
	case "tick":
		tm.TriggerTick()
	}
	// Always call View to catch rendering panics.
	_ = tm.model.View()
}
